### ISSUE TITLE
it always thinks there are too many arguments

### ISSUE THREAD

**Issue by Atomic-Germ** [user-none/csotools#1]
``` zsh
➜  psp csotools 7th\ Dragon\ 2020\ \(Japan\).iso 
usage: csotools [-h] [-l  LEVEL] [--version] [-s] in_file out_file
csotools: error: the following arguments are required: out_file
➜  psp csotools 7th\ Dragon\ 2020\ \(Japan\).iso 7th\ Dragon\ 2020\ \(Japan\)  
compress() takes at most 2 arguments (3 given)
```

**Comment by user-none** [comment]
The first one is correct, you only provided a file name for the input file and did not provide a second file to write the output to.

The second one is due to using a Python version that is too old for the tool. Python 3.11.0 or greater is required. This is because deflate needs to be passed a `wbits` value of -15 and this was not supported until Python 3.11.0. The pyproject.toml lists all dependencies and their minimum versions (which is only Python 3.11.0).
